services:
    common-job:
        build:
            context: .
            dockerfile: ./terrazzo-common/Dockerfile
        restart: no
    ui-job:
        build:
            context: .
            dockerfile: ./terrazzo-ui/Dockerfile
        restart: no
        depends_on:
            common-job:
                condition: service_completed_successfully
        volumes:
            - type: bind
              source: ${NSM_WWW_PATH}
              target: /www
        env_file:
            - .env
    api:
        build:
            context: .
            dockerfile: ./terrazzo-api/Dockerfile
        depends_on:
            common-job:
                condition: service_completed_successfully
            db-migrate:
                condition: service_completed_successfully
        ports:
            - "${API_PORT}:${API_PORT}"
            - "${SOCKET_PORT}:${SOCKET_PORT}"
            - "${SOCKET_ADMIN_PORT}:${SOCKET_ADMIN_PORT}"
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:${API_PORT}/"]
            interval: 15s
            timeout: 10s
            retries: 5
            start_period: 30s
        volumes:
            - type: bind
              source: ${VOLUME_PATH}/db
              target: /db
              bind:
                  create_host_path: true
        env_file:
            - .env

    db-migrate:
        build:
            context: .
            dockerfile: ./terrazzo-db/Dockerfile
        restart: "no"
        command: ["npm", "run", "migrate:up"]
        volumes:
            - type: bind
              source: ${VOLUME_PATH}/db
              target: /db
              bind:
                  create_host_path: true
        env_file:
            - .env
