services:
    api:
        build: .
        ports:
            - '${API_PORT}:${API_PORT}'
            - '${SOCKET_PORT}:${SOCKET_PORT}'
            - '${SOCKET_ADMIN_PORT}:${SOCKET_ADMIN_PORT}'
        restart: always
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://0.0.0.0:${API_PORT}/']
            interval: 15s
            timeout: 10s
            retries: 5
            start_period: 30s
        volumes:
            - type: bind
              source: ${DATABASE_PATH}
              target: ${DATABASE_PATH}
              bind:
                  create_host_path: true
        env_file:
            - .env