export enum LocalStorageKey {
    GITHUB_ACCESS_TOKEN = 'GITHUB_ACCESS_TOKEN',
}

export enum Role {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER',
    GUEST = 'GUEST'
}


export enum EventType {
    BOARD_CREATED = 'BOARD_CREATED',
    BOARD_UPDATED = 'BOARD_UPDATED',
    BOARD_DELETED = 'BOARD_DELETED',
    LIST_CREATED = 'LIST_CREATED',
    LIST_UPDATED = 'LIST_UPDATED',
    LIST_DELETED = 'LIST_DELETED',
    CARD_CREATED = 'CARD_CREATED',
    CARD_UPDATED = 'CARD_UPDATED',
    CARD_DELETED = 'CARD_DELETED',
    SPRINT_STARTED = 'SPRINT_STARTED',
    SPRINT_ENDED = 'SPRINT_ENDED',
    USER_ADDED_TO_BOARD = 'USER_ADDED_TO_BOARD',
    USER_REMOVED_FROM_BOARD = 'USER_REMOVED_FROM_BOARD',
    USER_PERMISSION_CHANGED = 'USER_PERMISSION_CHANGED',
    COMMENT_ADDED = 'COMMENT_ADDED',
    COMMENT_DELETED = 'COMMENT_DELETED',
    CHECKLIST_CREATED = 'CHECKLIST_CREATED',
    CHECKLIST_UPDATED = 'CHECKLIST_UPDATED',
    CHECKLIST_DELETED = 'CHECKLIST_DELETED',
    CHECKLIST_ITEM_CREATED = 'CHECKLIST_ITEM_CREATED',
    CHECKLIST_ITEM_UPDATED = 'CHECKLIST_ITEM_UPDATED',
    CHECKLIST_ITEM_DELETED = 'CHECKLIST_ITEM_DELETED',
    LABEL_CREATED = 'LABEL_CREATED',
    LABEL_UPDATED = 'LABEL_UPDATED',
    LABEL_DELETED = 'LABEL_DELETED',
    TIMESHEET_ENTRY_STARTED = 'TIMESHEET_ENTRY_STARTED',
    TIMESHEET_ENTRY_UPDATED = 'TIMESHEET_ENTRY_UPDATED',
    TIMESHEET_ENTRY_ENDED = 'TIMESHEET_ENTRY_ENDED',
    TIMER_STARTED = 'TIMER_STARTED',
    TIMER_STOPPED = 'TIMER_STOPPED',
    ROLLBACK_TO_EVENT = 'ROLLBACK_TO_EVENT'
}